REM @@@ START COPYRIGHT @@@
REM
REM (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
REM
REM  Licensed under the Apache License, Version 2.0 (the "License");
REM  you may not use this file except in compliance with the License.
REM  You may obtain a copy of the License at
REM
REM      http://www.apache.org/licenses/LICENSE-2.0
REM
REM  Unless required by applicable law or agreed to in writing, software
REM  distributed under the License is distributed on an "AS IS" BASIS,
REM  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
REM  See the License for the specific language governing permissions and
REM  limitations under the License.
REM
REM @@@ END COPYRIGHT @@@



COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLAllocEnv
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLAllocConnect
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBindParameter
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBrowseConnect
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLColumnAttribute
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLConnectDisconnect
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLDataSources
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLDescribeColumns
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLDriverConnect
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLDrivers
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLError
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLExecuteDirect
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLExecute
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLExtendedFetch
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLFetch
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetData
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLPutData
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetFunctions
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetInfo
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLMoreResults
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLAllocStmt
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBindColumn
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLColumns
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLDescribeParam
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetTypeInfo
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLPrimaryKeys
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API ResourceGoverning
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLSetConnectOption
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLSetCursorName
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLSetStatementOption
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLSpecialColumns
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLStatistics
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLTables
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLNativeSql
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLNumParams
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLNumResultCols
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLPrepare
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLRowCount
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLTransact
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLAllocHandle
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBindParameter30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLCloseCursor
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLColumnAttributes30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLCopyDescriptor
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLDescribeColumns30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLEndTran
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetConnectAttr
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetDescField
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetDescRec
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetDiagField
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetDiagRec
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetEnvAttr
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetInfo30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetStmtAttr
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLMoreResults30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBindCol30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetData30
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBindColInterval
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetDataInterval
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLBindParamInterval
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLForeignKeys
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLColumnPriv
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLTablePriv
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLGetTypeInfo3
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLProcedures
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLProcedureColumns
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLFetchScroll
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API Unicode
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API QueryID
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API Hash2
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API SQLCancel
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API LargeBlock
COAST.exe -d %ODBCTEST_DSN% -u %ODBCTEST_USER% -p %ODBCTEST_PASS% -c %ODBCTEST_CHARSET% -m %ODBCTEST_OS% -f API InfoStats

