# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# @@@ END COPYRIGHT @@@


./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLAllocEnv
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLAllocConnect
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBindParameter
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBrowseConnect
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLColumnAttribute
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLConnectDisconnect
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLDataSources
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLDescribeColumns
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLDriverConnect
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLDrivers
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLError
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLExecuteDirect
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLExecute
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLExtendedFetch
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLFetch
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetData
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLPutData
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetFunctions
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetInfo
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLMoreResults
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLAllocStmt
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBindColumn
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLColumns
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLDescribeParam
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetTypeInfo
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLPrimaryKeys
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API ResourceGoverning
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLSetConnectOption
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLSetCursorName
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLSetStatementOption
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLSpecialColumns
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLStatistics
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLTables
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLNativeSql
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLNumParams
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLNumResultCols
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLPrepare
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLRowCount
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLTransact
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLAllocHandle
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBindParameter30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLCloseCursor
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLColumnAttributes30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLCopyDescriptor
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLDescribeColumns30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLEndTran
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetConnectAttr
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetDescField
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetDescRec
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetDiagField
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetDiagRec
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetEnvAttr
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetInfo30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetStmtAttr
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLMoreResults30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBindCol30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetData30
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBindColInterval
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetDataInterval
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLBindParamInterval
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLForeignKeys
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLColumnPriv
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLTablePriv
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLGetTypeInfo3
#TRAF ./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLProcedures
#TRAF ./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLProcedureColumns
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLFetchScroll
# NOT FOR UNIX ./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API Unicode
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API QueryID
#TRAF ./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API Hash2
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API SQLCancel
#TRAF ./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API LargeBlock
./coast -d $ODBCTEST_DSN -u $ODBCTEST_USER -p $ODBCTEST_PASS -c $ODBCTEST_CHARSET -m $ODBCTEST_OS -f API InfoStats

date
echo ""
echo "Test Results for COAST TESTS"
echo "----------------------------"

grep -ih 'TEST RESULT' *.log | tee summary.sum

echo "-------------------"
echo "END OF COAST TESTS"

chmod -R 777 *

