#include "tokens.h"

   struct token_table{
      char string[25];
      short value;
      };
   typedef struct token_table token_table;

/* NOTE: some tokens are used more than once */
#define NUMBER_OF_TOKENS    76

   token_table token[NUMBER_OF_TOKENS] = {
      {"STARTUP",STARTUP},
      {"ALLPROCESSES",ALL_PROCESSES},
      {"CLEANUP",CLEANUP},
      {"CREATE",CREATE_KW},
      {"USE",USE},
      {"MAXIMUMRECORDS",MAX_RECORDS},
      {"RECORDRANGE",RECORD_RANGE},
      {"REPEAT",REPEAT},
      {"PROCESS",PROCESS},
      {"PROCESSES",PROCESS},
      {"KEYSEQUENCED",KEY_SEQ_KW},
      {"ENTRYSEQUENCED",ENTRY_SEQ_KW},
      {"RELATIVE",RELATIVE_KW},
      {"TABLE",TABLE},
      {"TABLES",TABLE},
      {"LIKE",LIKE},
      {"WITH",WITH},
      {"COLUMN",COLUMNS},
      {"COLUMNS",COLUMNS},
      {"ABORT",ABORT_KW},
      {"FOR",FOR_KW},
      {"MINUTE",MINUTES},
      {"MINUTES",MINUTES},
      {"HOUR",HOURS},
      {"HOURS",HOURS},
      {"FOREVER",FOREVER},
      {"RANDOM",RANDOM_KW},
      {"RANDOMLY",RANDOM_KW},
      {"SEQUENTIAL",SEQUENTIAL},
      {"SEQUENTIALLY",SEQUENTIAL},
      {",",COMMA},
      {";",SEMI_COLON},
      {"-",DASH},
      {"=",EQUALS},
      {"(",BEGIN_LIST},
      {")",END_LIST},
      {"{",BEGIN_BLOCK},
      {"}",END_BLOCK},
      {"TESTID",TESTID},
      {"WORKVOLUME",WORK_VOL},
      {"TABLEVOLUME",TABLE_VOL},
      {"INSERTS",INSERT},
      {"INSERT",INSERT},
      {"DELETES",DELETE_ROW},
      {"DELETE",DELETE_ROW},
      {"UPDATES",UPDATE},
      {"UPDATE",UPDATE},
      {"SELECTS",SELECT},
      {"SELECT",SELECT},
      {"TIMES",TIMES},
      {"TRANSACTIONSIZE",TRANSACTION_SIZE},
      {"CONCURRENTCONNECTIONS",CONCURRENT_CONNECTIONS},
      {"SEQUENTIALSUBSETSIZE",SUBSET_SIZE},
      {"VSBBSUBSETSIZE",VSBB_SIZE},
      {"RUNTIME",RUNTIME},
      {"SEED",SEED},
      {"CHECKINTERVAL",CHECK_INTERVAL},
      {"UNTILDONE",UNTIL_DONE},
      {"ALL",ALL},
      {"VSBB",VSBB},
      {"RUNTIMELIBRARY",LIBRARY},
      {"FILL",FILL},
      {"RECORD",RECORD},
      {"RECORDS",RECORD},
      {"TO",TO_KW},
      {"AUDITED",AUDITED},
      {"NONAUDITED",NONAUDITED},
      {"ADD",ADD},
      {"COLUMN",COLUMN},
      {"ALTER",ALTER_KW},
      {"UPDATEM", UPDATE_M},
      {"UPDATEMS", UPDATE_M},
      {"SETTESTPOINT", SETTESTPOINT},
      {"CLEARTESTPOINT", CLEARTESTPOINT},
      {"DTCTRANSACTIONS",DTC_TRANSACTIONS},
      {"STOPONERROR", STOP_ON_ERROR_KW}
       };
